####VSCODE RUN 

version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093

  # kafka-app:
    # build: .
    # container_name: kafka-spring-app
    # restart: always
    # depends_on:
    #   - kafka
    # ports:
    #   - "8080:8080"
    # environment:
    #   SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


#DOCKER RUN

# version: '3.8'

# services:
#   zookeeper:
#     image: bitnami/zookeeper:latest
#     container_name: zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes

#   kafka:
#     image: bitnami/kafka:latest
#     container_name: kafka
#     ports:
#       - "9092:9092"
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#     depends_on:
#       - zookeeper

#   springboot-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: springboot-app
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#     depends_on:
#       - kafka
#     volumes:
#       - D:/kafka-docker/data:/bitnami/kafka
      
      